# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62f8871ef0336530aa40e61d365b0d5cd9e8585d0b0188f4a5859f86001fdf9c41c951b5212179d1d1665e6d4448e5f543e1a63f229d36bd65cf592099e61d5e

test:
  secret_key_base: fae037640c58de00426e23cab19ed3e57b9e7dce6bb74c73ba97c14201438d926b0df966fb53d0a85b36225d61d1d1f85a49dcd75b5445bd4e3944599e60af89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
